version: '3.7'

services:
  node:
    container_name: ${PROJECT_NODE_NAME}__node
    image: node:latest
    working_dir: /srv/app
    volumes:
      - .:/srv/app
      - build:/srv/app/build
      - /srv/app/node_modules
    tty: true
    command: sh -c "npm ci && npm run production"

volumes:
  build:
