version: "3.7"

services:
  node:
    container_name: vite_docker_node
    image: node:alpine
#    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./src
        target: /srv/app
    tty: true
    command: sh -c "npm i && npm run dev"
