version: "3.7"

services:
  node:
    stdin_open: true
    tty: true
    container_name: vite_docker_node
    image: node:latest
    ports:
      - ${DEV_APP_PORT}:3000
    working_dir: /app
    volumes:
      - type: bind
        source: ./src
        target: /app
    command: sh -c "yarn install && yarn start"
