version: '3.7'

services:
  nginx:
    container_name: partner_moderator_panel_front__nginx
    image: nginx:alpine
    working_dir: /app/build
    volumes:
      - build:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${PROD_APP_PORT}:80
    command: sh -c "nginx -g 'daemon off;'"

  node:
    container_name: ${PROJECT_NODE_NAME}__node
    image: node:latest
    working_dir: /app
    volumes:
      - ./src:/app
      - build:/app/build
      - /var/node:/app/node_modules
    tty: true
    command: sh -c "yarn install --frozen-lockfile && yarn production"

volumes:
  build:
